version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cnpm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnpm_db
    ports:
      - "3307:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: